### ISSUE TITLE
Quiz 2 Planning

### ISSUE THREAD

**Issue by Page007** [Page007/rutvikpage#4]
Following are the things on the to-do list for Analysis: 

- [x] Lectures revision 
- [ ] PSET 2, PSET 3 including optional problems
- [ ] Ex. 3.1.5 3.2.1, 3.2.5, 3.3.1, 3.3.4, 3.3.5, 3.3.10, 3.4.3, 3.4.4, 3.4.8 Lindstrøm's book.
- [x] Ex. 3.2.10, 3.3.10, 3.3.17, 3.3.20, 3.3.33, 3.5.4, 3.5.9 from Boller's textbook. 
- [ ] Examples 4 and 5 from lecture 15.

**Comment by rutvikpage** [comment]
Following is the exam structure of the quiz: 

1. TF rapid fire 
2. Topology of metric spaces
3. Continuity of metric spaces
4. Cauchy sequences in metric spaces -- question on completeness.

**Comment by rutvikpage** [comment]
To score nice marks on the bonus question also, towards the end of prep, go to the Lindstrom and Boller book, refer to chapters on completeness and check out the exercises!
