### ISSUE TITLE
TO DO: Thursday 25 apr 2024

### ISSUE THREAD

**Issue by Page007** [Page007/rutvikpage#5]
Meeting with Scott: 

## Main Issue
1. Overall Distribution of Payment Amount
2. State Specific Distribution of Payment Amount
3. Condition on Industry Code -- heterogeneity in payment amounts across industry codes -- nationally. 

A later to-do would be to find the distribution of payment amounts at a state X industry code level to find the most "suitable" filing fee that could be attributed to a state. 

## Filing Fee Variation : Cleaning Issues
1. Make a list of across jurisdictions issues. -- take a call on whether we need RAs for this. 
2. Make a list of jurisdiction specific issues. -- do a cost benefit on this. 

## Third Wheel 
1. Interaction between treatment and income shares with CIs plotted to check the gradient.

**Comment by rutvikpage** [comment]
|                | Conditional On Industry Codes | Not conditional on industry codes | 
|:---------:|:------------------------------:|:----------------------------------:| 
| National |                                                       |                                                            |
| State wise |                                                   |                                                            |

**Comment by rutvikpage** [comment]
![Screenshot 2024-04-25 at 2 03 29 PM](https://github.com/Page007/rutvikpage/assets/38257711/34ea74aa-b0ce-4d29-a68d-6dd864a0c1ac)

Collapse the monthly individual level public records raw data to a (subjectKey, filedDate, paymentAmount) level and then summarize the payment amount.
