### ISSUE TITLE
Within and Across Jurisdictions wishlist

### ISSUE THREAD

**Issue by Page007** [Page007/rutvikpage#7]
Across Jurisdictions: 
Go to raw data and check: 

1. Debt Collection specific/ consumer credit specific fees for each state. -- flag states like CA and NY where we see separate filing categories for plaintiffs with 12+ suits. 
2. Check if we missed smaller claims courts (for example village courts, city courts, etc.) -- especially in those states where the median payment amount/filing fee ratio small compared to other states. 
3. Mis-labelled filing categories -- for example OR
4. Drop Courts within a jurisdiction that don't deal with debt collection lawsuits -- for example, a state Supreme court will most probably not deal with credit card debt collection lawsuits.

Jurisdiction Specific: 

1. Filing categories, fees and thresholds are absent in TN.
2. Thresholds are absent in TX. 
3. Following states' web archive may be fished out to get data on a subset of courts present in a subset of years between 2009-17: AR, AZ, HI, IA, ID, IN, MD, ME, MI, NE, VT, WI..

**Comment by rutvikpage** [comment]
To find out how many states at a court level have a "menu" of filing fees? Dataset [here](https://www.dropbox.com/scl/fi/5o5n8tmewuwlzk7j01szs/numThresholds.dta?rlkey=bjbxuoi2v30rw6qchjc7jgkir&dl=0).
Here, we have restricted the filing fee panel to: 

1. Years between 2009-17
2. Dropped jurisdictions that have missing minimum and maximum thresholds
3. 5 out of 22 states are such that small claims fees have >= 3 "menus" -- following states: 
<img width="763" alt="Screenshot 2024-05-01 at 12 19 29 AM" src="https://github.com/Page007/rutvikpage/assets/38257711/2d1cca90-d0f5-4a57-a4cd-d20f63ec535b">

4. 3 out of 21 states are such that civil filing fees have >= 3 "menus": 

<img width="766" alt="Screenshot 2024-05-01 at 12 24 11 AM" src="https://github.com/Page007/rutvikpage/assets/38257711/73479294-3727-4566-b0b8-dd679fbbd57a">
