### ISSUE TITLE
Finals Prep

### ISSUE THREAD

**Issue by Page007** [Page007/rutvikpage#9]
Following things need to be done before the finals: 

1. Definition of Equicontinuity
2. Statement of Arzela Ascoli
3. Example in Last Lecture by Haoyang
4. Problem sets -- complete solutions 
5. Book questions and concepts -- this helps in applying the definitions and concepts learned again and again. So, this is necessary.

**Comment by rutvikpage** [comment]
Revisit the corollaries of Arzelá-Ascoli theorem -- especially examples.

**Comment by rutvikpage** [comment]
Thanks for this -- it was absolutely stunning. I was one of the highest in the cohort, so it was all fine in the end.
